---
- hosts: loadbalancer
  become: true
  tasks:
    #- name: EPEL packaes
     # yum:
      # name:  name=epel-release
       #state: latest

    - name: install nginx
      yum:  
        name=nginx 
        state=present
        update_cache=true
    
    - name: start nginx  
      service:
        name=nginx
        state=started 
      notify: 
        - start nginx

  handlers:
    - name: start nginx
      become: true
      service: name=nginx  enabled=yes state=started

